In [1]:
import numpy as np

In [10]:
# all zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# all ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# all same integer
np.full((2,3),51)

array([[51, 51, 51],
       [51, 51, 51]])

In [13]:
# numbers in a sequence of range
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
# take shape of another array
a=np.array([[3.7,1.2,52.5,3.54,65.91],[50,7,99,0,794]])
b=np.full((a.shape),23)
# newArray=np.full_like(|oldArrayName|.shape,|number|)
c=np.full_like(a,85)
print(b)
print(c)

[[23 23 23 23 23]
 [23 23 23 23 23]]
[[85. 85. 85. 85. 85.]
 [85. 85. 85. 85. 85.]]


random numbers

In [23]:
# random decimal
# np.random.rand(rows,columns)
np.random.rand(2,5)

array([[0.79276898, 0.53996663, 0.30167654, 0.39444786, 0.41441798],
       [0.2677718 , 0.04244017, 0.58173701, 0.88663321, 0.84216539]])

In [26]:
# random integer
# np.random.randint(smallest number,highest number,size=(rows,columns))
np.random.randint(5,8,size=(3,4))

array([[5, 6, 7, 7],
       [5, 7, 7, 7],
       [5, 7, 5, 7]])

In [28]:
# Identity Matrix: square matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
# repeation of array
a=np.array([[1,2,3]])
print(f"array a: {a}")
# np.repeat(arrayRepeat,number of rows,axis=0)
np.repeat(a,5,axis=0)

array a: [[1 2 3]]


array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])