In [1]:
import numpy as np

In [2]:
a=np.array([1,5,9])

In [6]:
# addition
a+2

array([ 3,  7, 11])

In [8]:
# subsctraction
a-2

array([-1,  3,  7])

In [9]:
# multiplication
a*2

array([ 2, 10, 18])

In [10]:
# division
a/2

array([0.5, 2.5, 4.5])

In [11]:
# exponents
a**2

array([ 1, 25, 81], dtype=int32)

In [12]:
# trignometry
np.sin(a)

array([ 0.84147098, -0.95892427,  0.41211849])