In [1]:
import numpy as np

In [10]:
a=np.array([1,3,5,7])
a

array([1, 3, 5, 7])

In [11]:
b=np.array([2,4,6,8])
b

array([2, 4, 6, 8])

In [12]:
a+b

array([ 3,  7, 11, 15])

In [13]:
a-b

array([-1, -1, -1, -1])

In [14]:
a*b

array([ 2, 12, 30, 56])

In [15]:
a**b

array([      1,      81,   15625, 5764801], dtype=int32)

In [16]:
a/b

array([0.5       , 0.75      , 0.83333333, 0.875     ])

In [17]:
a**(1/b)

array([1.        , 1.31607401, 1.30766049, 1.27537311])