In [1]:
import numpy as np

In [23]:
array=np.array([[1,5,9],[2,6,8]])

In [24]:
type(array)

numpy.ndarray

In [25]:
array.ndim

2

In [26]:
array.shape

(2, 3)

In [27]:
array.size

6

In [28]:
array.dtype

dtype('int32')

In [29]:
floatarray=np.array([[1,5,9],[2,6,8]], dtype='float')

In [30]:
floatarray

array([[1., 5., 9.],
       [2., 6., 8.]])

In [31]:
floatarray.dtype

dtype('float64')

In [32]:
complex=np.array([[1,5,9],[2,6,8]], dtype='complex')

In [33]:
complex

array([[1.+0.j, 5.+0.j, 9.+0.j],
       [2.+0.j, 6.+0.j, 8.+0.j]])

In [34]:
complex.dtype

dtype('complex128')

In [35]:
tuple=np.array((1,2,3))

In [36]:
tuple

array([1, 2, 3])

In [38]:
tuple.dtype

dtype('int32')

In [39]:
zeroarray=np.zeros((3,4))

In [40]:
zeroarray

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
complexfull=np.full((3,3),6,dtype='complex')

In [47]:
complexfull

array([[6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j]])

In [53]:
randomnumber=np.random.random((2,2))

In [54]:
randomnumber

array([[0.80022739, 0.80362879],
       [0.07601313, 0.70979097]])

In [57]:
arrangenumbers=np.arange(1,50,5)

In [59]:
arrangenumbers

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])