In [1]:
import numpy as np

In [17]:
a=np.array([[3.7,1.2,52.5,3.54,65.91],[50,7,99,0,794]])

In [18]:
print(a)

[[  3.7    1.2   52.5    3.54  65.91]
 [ 50.     7.    99.     0.   794.  ]]


In [19]:
# get specific element
# array[row,column]
# rows: 0,1,2,...
# columns: 0,1,2,...
a[1,2]

99.0

In [20]:
# get specific row
# array[row,:]
a[1,:]

array([ 50.,   7.,  99.,   0., 794.])

In [21]:
# get specific column
# array[:,column]
a[:,1]

array([1.2, 7. ])

In [26]:
# get specific set of elements
# silcing wit index position
# array[row,start-index:end-index:step-seize]
a[0,1:5:2]

array([1.2 , 3.54])