In [1]:
import numpy as np

In [2]:
a=np.array([[3.7,1.2,52.5,3.54,65.91],[50,7,99,0,794]])

In [3]:
a

array([[  3.7 ,   1.2 ,  52.5 ,   3.54,  65.91],
       [ 50.  ,   7.  ,  99.  ,   0.  , 794.  ]])

In [5]:
# replace element
a[0,2]=54.6
a

array([[  3.7 ,   1.2 ,  54.6 ,   3.54,  65.91],
       [ 50.  ,   7.  ,  99.  ,   0.  , 794.  ]])

In [6]:
# replace row
a[0,:]=[6.1,2.5,96.2,5.27,75.34]
a

array([[  6.1 ,   2.5 ,  96.2 ,   5.27,  75.34],
       [ 50.  ,   7.  ,  99.  ,   0.  , 794.  ]])