In [1]:
import numpy as np

In [5]:
# numpy array of anges
angles=np.array([0,30,45,60,90,180])
angles

array([  0,  30,  45,  60,  90, 180])

In [6]:
# convert degree into randians
radians=np.deg2rad(angles)
radians

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633,
       3.14159265])

In [42]:
# convert radians to degree
degree=np.rad2deg(radians)
degree

array([  0.,  30.,  45.,  60.,  90., 180.])

In [13]:
# trigonometric

In [14]:
# sine
sine=np.sin(radians)
sine

array([0.00000000e+00, 5.00000000e-01, 7.07106781e-01, 8.66025404e-01,
       1.00000000e+00, 1.22464680e-16])

In [19]:
# cosine
cosine=np.cos(radians)
cosine

array([ 1.00000000e+00,  8.66025404e-01,  7.07106781e-01,  5.00000000e-01,
        6.12323400e-17, -1.00000000e+00])

In [23]:
# tangent
tangent=np.tan(radians)
tangent

array([ 0.00000000e+00,  5.77350269e-01,  1.00000000e+00,  1.73205081e+00,
        1.63312394e+16, -1.22464680e-16])

In [20]:
# inverse trigonometric

In [29]:
# inverse sine
sine_inverse=np.arcsin(sine)
sine_inverse

array([0.00000000e+00, 5.23598776e-01, 7.85398163e-01, 1.04719755e+00,
       1.57079633e+00, 1.22464680e-16])

In [30]:
# inverse cosine
cosine_inverse=np.arccos(cosine)
cosine_inverse

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633,
       3.14159265])

In [31]:
# hyperbolic trigonometry

In [32]:
# hyperbolic sine
sine_hyperbolic=np.sinh(radians)
sine_hyperbolic

array([ 0.        ,  0.54785347,  0.86867096,  1.24936705,  2.3012989 ,
       11.54873936])

In [33]:
# hyperbolic cosine
cosine_hyperbolic=np.cosh(radians)
cosine_hyperbolic

array([ 1.        ,  1.14023832,  1.32460909,  1.60028686,  2.50917848,
       11.59195328])

In [36]:
# inverse trigonometric hyperbolic

In [37]:
# inverse sine hyperbolic
inverse_sine_hyperbolic=np.arcsinh(sine_hyperbolic)
inverse_sine_hyperbolic

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633,
       3.14159265])

In [39]:
# inverse cosine hyperbolic
inverse_cosine_hyperbolic=np.arccosh(cosine_hyperbolic)
inverse_cosine_hyperbolic

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633,
       3.14159265])