In [1]:
import numpy as np

In [2]:
# construct an array of even and odd numbers
even = np.array([0, 2, 4, 6, 8, 16, 32])
odd = np.array([1, 3, 5, 7, 9, 17, 33])

In [3]:
# bitwise operations

In [4]:
# and
np.bitwise_and(even,odd)

array([ 0,  2,  4,  6,  8, 16, 32], dtype=int32)

In [5]:
# or
np.bitwise_or(even,odd)

array([ 1,  3,  5,  7,  9, 17, 33], dtype=int32)

In [6]:
# xor
np.bitwise_xor(even,odd)

array([1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [7]:
# invert or not
np.invert(even)

array([ -1,  -3,  -5,  -7,  -9, -17, -33], dtype=int32)

In [8]:
# left shift
np.left_shift(even,1)

array([ 0,  4,  8, 12, 16, 32, 64], dtype=int32)

In [9]:
# right shift
np.right_shift(even,1)

array([ 0,  1,  2,  3,  4,  8, 16], dtype=int32)