In [1]:
import numpy as np

In [2]:
a = np.array([[12, 15], [10, 1]])
a

array([[12, 15],
       [10,  1]])

In [14]:
# .sort()
'''
returns a sorted copy of an array.
'''

'\nreturns a sorted copy of an array.\n'

In [10]:
# first axis
np.sort(a,axis=0)

array([[10,  1],
       [12, 15]])

In [11]:
# last axis
np.sort(a,axis=-1)

array([[12, 15],
       [ 1, 10]])

In [12]:
# no axis
np.sort(a,axis=None)

array([ 1, 10, 12, 15])

In [15]:
# .argsort()
'''
returns inddices that would sort an array
'''

'\nreturns inddices that would sort an array\n'

In [18]:
a = np.array([9, 3, 1, 7, 4, 3, 6])
a

array([9, 3, 1, 7, 4, 3, 6])

In [21]:
b=np.argsort(a)
b

array([2, 1, 5, 4, 6, 3, 0], dtype=int64)

In [22]:
c = np.zeros(len(b), dtype = int)
for i in range(0, len(b)):
    c[i]= a[b[i]]
c

array([1, 3, 3, 4, 6, 7, 9])